version: '2'

services:
    service:
       image: acmeshop-cart:latest
       hostname: cartservice
       restart: always
       ports:
          - '5000:5000'
       cap_drop:
           - all
       cap_add:
           - NET_BIND_SERVICE
       read_only: true
    redis:
       image: redis:5.0.3-alpine
       hostname: cartredis
       restart: always
       cap_drop:
           - all
       cap_add:
           - NET_BIND_SERVICE
       ports:
           - '6379:6379'
